name: flutter_starter_cli
description: A command line tool that provides ease of setting up a Flutter project.
version: 0.0.1-dev.4

homepage: https://flutter-starter.geekyants.com
repository: https://github.com/GeekyAnts/flutter-starter-cli

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  mason_logger: ^0.2.6
  path: ^1.8.3
  pub_updater: ^0.3.1

dev_dependencies:
  flutter_lints: ^2.0.1

executables:
  flutter_starter_cli:
