name: flutter_starter_cli
description: Flutter Starter CLI
version: 0.0.1-dev.1

homepage: https://flutter-starter.geekyants.com
repository: https://github.com/GeekyAnts/flutter-starter-cli

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.2.0
  path: ^1.8.2
  pub_updater: ^0.2.1

dev_dependencies:
  flutter_lints: ^2.0.1

executables:
  flutter_starter_cli:
