name: flutter_starter_cli
description: Flutter Starter CLI
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.1.3
  path: ^1.8.2
  pub_updater: ^0.2.1

dev_dependencies:
  flutter_lints: ^2.0.1

executables:
  flutter_starter_cli:
