name: {{name}}
description: {{desc}}

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  http:
  http_interceptor: ^1.0.2
  shared_preferences: ^2.0.12
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  built_value: ^8.4.1
  json_annotation: ^4.6.0
  bloc: ^8.1.0
  go_router: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_native_splash: ^2.0.2
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  built_value_generator: ^8.4.1
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter_native_splash:
  image: assets/images/logo.png
  color: "5E92F3"
  android_disable_fullscreen: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png
    - assets/images/login.png
    - assets/images/signup.png
