name: flutter_starter_cli
description: Flutter Starter CLI
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason: ^0.1.0-dev.33
  mason_logger: ^0.1.3
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  flutter_lints: ^2.0.1

executables:
  flutter_starter_cli:
